
services:
  php:
    build: .
    container_name: php-api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      #- DB_HOST=db
      #- DB_NAME=postgres
      #- DB_USER=postgres
      #- DB_PASS=secret
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      

 
  # db:
  #   image: postgres:16
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #   ports:
  #    - "5433:5432"
  #   volumes:
  #    - db_data:/var/lib/postgresql/data


      
  # db:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: mi_base_datos
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql

  #phpmyadmin:
   # image: phpmyadmin/phpmyadmin
   # container_name: phpmyadmin
   # restart: always
   # ports:
   #   - "8081:80"
   # environment:
   #   - PMA_HOST=db
   #  - MYSQL_ROOT_PASSWORD=secret

volumes:
  db_data:
